### ISSUE TITLE
Bug or feature request: different Next Steps settings for each board

### ISSUE THREAD

**Issue by xtoq** [adrienjoly/chrome-next-step-for-trello#48]
I have no idea if it's always worked this way and I'm just incredibly unobservant or if something happened recently, but now the Next Steps setting is the same for all my boards. Not ideal for my use case, and I'd imagine others who have different roles they perform in each board.

Please let me know what additional information I can provide! Thanks.

**Comment by adrienjoly** [comment]
Hi @xtoq ,
Thanks for proposing this issue.
The settings are shared across boards on purpose, so this is not a bug.
Feel free to fork this repo and make your own version of Next Step for Trello :-)

**Comment by xtoq** [comment]
I might just do that. Of course, I have to find the free time. XD

Just out of curiosity, do you know how others without coding experience get around this issue? For example, I use Trello with clients and I have boards for their projects that are shared with them then backend production boards that are just for me. For the backend boards, I want to see all the tasks in Next Steps but for the client-facing ones I only want to see the Next Step as they are usually checklists for the client to complete and I need simply need the high level of where they are in the process. 

Wondering about use case, to see if I could justify moving it up my priority list. ;)

Thanks for your reply!

**Comment by adrienjoly** [comment]
Actually, the selected mode was not persisted by the extension, in the past. And many users would complain because they had to re-select their favorite mode every time. That's way I decided to store each user's preference in a cookie.

I don't remember having users asking for per-board settings, but you can still check in the "reviews" and "assistant" tabs of [the extension's page on chrome web store](chrome.google.com/webstore/detail/next-step-for-trello-card/iajhmklhilkjgabejjemfbhmclgnmamf).

**Comment by adrienjoly** [comment]
yet another request on CWS:

> Leah GreerModified 5 juil. 2017
> Nice idea but could use some improvement for me to really use it.
> I second the request for different setting per board. I use checklists differently across boards.

**Comment by adrienjoly** [comment]
Also suggested by Brick Freedom: "Switching on and off per board"

> Hey
> 
> Great little extension you have here.
> 
> A great feature would be the ability to set it per board instead of a global setting.
> 
> I want to switch it off on certain boards. :)

**Comment by xtoq** [comment]
ACK! I clearly need to fork this. I wish I could fork my calendar and find extra time.

Any tips or best practices before I start on this (hopefully this weekend)? I'd love it to be something that could eventually be an option in Next Steps, so if you have any caveats I'd love to hear them!

**Comment by adrienjoly** [comment]
Awesome, @xtoq !

The only caveats/recommendations at can think of, if you want your fork to be integrated into Next Step for Trello:

- add as little code as possible
- follow the coding style of the current code base
- include automated tests
- make it so the default functionality remains unchanged (i.e. current mode is common to all boards), and integrate a "preferences" dialog for power-users to change the settings (e.g. per-board modes)

Let me know, if you have any questions!
