### ISSUE TITLE
View 1 checklist in full

### ISSUE THREAD

**Issue by mikeday1983** [adrienjoly/chrome-next-step-for-trello#49]
It would be great to select a checklist to view in full.  Instead of seeing all items from all checklists, select a checklist and it only displays the items from that one.

**Comment by adrienjoly** [comment]
Hi Mike!
Good idea!
In v1.8.8, I implemented a new "First checklist" mode that displays all the tasks of the each card's first checklist only, without prefix. It should be available shortly on the Chrome Web Store.
Does that solve your need?
Adrien
