### ISSUE TITLE
Javascript error when updating a card with a checklist

### ISSUE THREAD

**Issue by stevecshanks** [adrienjoly/chrome-next-step-for-trello#54]
I've noticed that when you update a card with a checklist (e.g. by ticking off an item or moving the card to a different list), the "next step" disappears and you get the following in the console log:

![screen_shot_2017-07-03_at_14 20 11](https://user-images.githubusercontent.com/24637079/27794786-7ae155aa-5ffb-11e7-82f1-d1ede508dc34.png)

I haven't dug into what might be causing this, but happy to take a look later this week if you'd like a second pair of eyes?

**Comment by adrienjoly** [comment]
Thanks for letting me know, Steve!

It's probably caused by the fact that Trello changed the structure of the DOM. I had made a fix, but you may have found an edge case. (e.g. checking the last item of a cast)

Here is the fix I had applied: https://github.com/adrienjoly/chrome-next-step-for-trello/commit/5ed4540c8dafb994948a1d050f0cef3aaccf58ae

Feel free to propose a pull request if you feel like it! Otherwise, I'll have a look at it in a few days.

**Comment by adrienjoly** [comment]
...Oh, you may want to make sure that you're using the latest version: v1.8.11

**Comment by stevecshanks** [comment]
I've made _some_ progress on this - you can see a work-in-progress here:

https://github.com/stevecshanks/chrome-next-step-for-trello/commit/b7c88a903f47bc0172b11ffb444bc3be3c331a4c

This fixes the two issues I'd encountered, but I'm still having trouble with boards containing multiple cards with checklists.  Unsure if that's an issue I've created, or if the fixes I've done just don't cover all the possible scenarios.  I'll keep looking into it!

I've added an "expected" card HTML file and a few tests which will try and pick out the relevant elements from it.  Will hopefully be useful next time Trello make changes!

There is unfortunately quite a bit of duplication between the two test files.  I briefly looked at having a "boilerplate" file, but I don't yet know enough about Javascript modules to make much progress.

**Comment by stevecshanks** [comment]
Turned out not to be an issue with multiple cards, but with the "active-card" class name being added out-of-order.  Had a similar issue with the "is-covered" class for cards with images.

I think this fixes both: https://github.com/stevecshanks/chrome-next-step-for-trello/commit/3cc0743860a6ff1d7fabc125b1990751cb09e542

Will keep using over the next few days and then send you a PR if no more issues crop up!

**Comment by adrienjoly** [comment]
This is awesome, Steve! Thanks for having taken the time to troubleshoot and share your findings on this issue! 💪
Can't wait to see your PR!
