### ISSUE TITLE
UI: add some space between check box and text of list item

### ISSUE THREAD

**Issue by adrienjoly** [adrienjoly/chrome-next-step-for-trello#73]
Reported by Egor, by email:

> hey guys, your extension is very useful, but, could you please add some space between check box and text of list item. thanks!

Screenshots taken from Adrien's Mac with Chrome 67.0.3396.99:

<img width="79" alt="screen shot 2018-07-07 at 17 56 24" src="https://user-images.githubusercontent.com/531781/42412576-2ba77528-820f-11e8-97c1-12430f469fc7.png">

<img width="38" alt="screen shot 2018-07-07 at 17 56 31" src="https://user-images.githubusercontent.com/531781/42412572-22cd7db2-820f-11e8-9dd6-5389e2d69e50.png">

**Comment by nellyk** [comment]
@adrienjoly  can i work on this issue
