### ISSUE TITLE
Refresh glyph causes UI jitter

### ISSUE THREAD

**Issue by alejandro5042** [adrienjoly/chrome-next-step-for-trello#79]
Every time you close a card, it refreshes and causes the UI to "jitter". This is annoying since the human eye is attracted to motion.

Example:

![trello-refresh-jitter](https://user-images.githubusercontent.com/3143819/51355967-67221880-1a7e-11e9-9d76-58d07514acd2.gif)

I suggest:

- Only show the glyph if the refresh is taking longer than 1 or 2 seconds
- Replace the `AJ` initials with the glyph when it is active

**Comment by adrienjoly** [comment]
Hi Alejandro, thanks for reporting this!

In that case, I think that replacing the initials by the loading animation (when it's (re)loading) would be ok.

I'm not sure I'll find enough time to do that shortly. Would you like to propose a PR to fix this?
