### ISSUE TITLE
Extension stop working (Chrome 74.0.3729.169 - 64 bits) Win10

### ISSUE THREAD

**Issue by JulianPardo** [adrienjoly/chrome-next-step-for-trello#80]
When open or reload trello.com the extension stuck at loading without make any change on the web or display the complete lists

- I tested after restart windows 
- The error persist after using a clean profile on chrome

What other information can I provide to help solve this error?

Tnx :D

**Comment by adrienjoly** [comment]
Hi Julien! Thanks for reporting this issue!

There are two things you can try:
- try to disable all your Chrome extensions except Next Step for Trello
- press Ctrl-Alt-J to open the JavaScript console, refresh the Trello page, and copy+paste the contents of the JavaScript console here, so I can see if there's anything failing on your side.

**Comment by JulianPardo** [comment]
Thanks for the help! :D

DevTools failed to parse SourceMap: https://trello.com/b/ZWqyprtF/perf.1ac91fd06f99c80feb0c.js.map
next-step-for-trello.user.js:249 Uncaught (in promise) TypeError: Cannot read property 'getElementsByClassName' of undefined
    at getUserName (next-step-for-trello.user.js:249)
    at renderAtMention (next-step-for-trello.user.js:404)
    at String.replace (<anonymous>)
    at renderMarkdownSymbols (next-step-for-trello.user.js:414)
    at renderMarkdown (next-step-for-trello.user.js:457)
    at renderItem (next-step-for-trello.user.js:473)
    at Array.map (<anonymous>)
    at setCardContent (next-step-for-trello.user.js:530)
    at next-step-for-trello.user.js:543
    at Array.forEach (<anonymous>)
getUserName @ next-step-for-trello.user.js:249
renderAtMention @ next-step-for-trello.user.js:404
renderMarkdownSymbols @ next-step-for-trello.user.js:414
renderMarkdown @ next-step-for-trello.user.js:457
renderItem @ next-step-for-trello.user.js:473
setCardContent @ next-step-for-trello.user.js:530
(anonymous) @ next-step-for-trello.user.js:543
updateCardElements @ next-step-for-trello.user.js:540
(anonymous) @ next-step-for-trello.user.js:565
Promise.then (async)
updateCards @ next-step-for-trello.user.js:550
main @ next-step-for-trello.user.js:669
(anonymous) @ next-step-for-trello.user.js:681
setInterval (async)
init @ next-step-for-trello.user.js:679
(anonymous) @ next-step-for-trello.user.js:690
(anonymous) @ next-step-for-trello.user.js:692

**Comment by jerzygangi** [comment]
@adrienjoly 

I'm seeing the same thing on Mac Chrome:

<img width="1129" alt="Screen Shot 2019-06-01 at 11 48 55 PM" src="https://user-images.githubusercontent.com/1406581/58757835-e4977400-84c7-11e9-9e5f-32b4edd3db7f.png">

**Comment by adrienjoly** [comment]
Interesting !
Can you confirm that you are properly logged in, on trello ?

**Comment by adrienjoly** [comment]
Hi Julian and Jerzy!

Indeed, Trello seem to have changed the way they expose the username => I fixed this in the version 1.11.0 of the extension => it should be updated on your browser soon!

Thanks for your help!

**Comment by jerzygangi** [comment]
Thanks @adrienjoly. Just pulled 1.11.0 and it's working.

Slightly OT: saw in the commit log you removed the donate link. Do you have a place where you still accept donations?

**Comment by adrienjoly** [comment]
Awesome, thanks for the feedback, Jerzy! 🕺

I did remove the donate link to replace it with a native ad.

If you still want to send me a donation -- which is always appreciated 🤗 -- you can do it from my personal website: https://adrienjoly.com/donate/

Thank you Jerzy, and have a great day! ☀️

**Comment by JulianPardo** [comment]
This extension is essential for my workflow. When it failed, I looked for an alternative to be able to work normally, but it doesn't exist. Thanks a lot for your help, this really is an incredible piece of code...

I'm already scheduled to make the donation. Tnx

**Comment by adrienjoly** [comment]
Thank you so much for your kind message, Julian! <3
